/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;

/**
 *
 * @author Ababacar
 */
public class GestionnaireForm extends javax.swing.JFrame {

    /**
     * Creates new form GestionnaireForm
     */
    
    Color DefaultColor, ClickedColor;
    public GestionnaireForm() {
        initComponents();
         DashboardGestionnaire dashboardGestionnaire = new DashboardGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(dashboardGestionnaire).setVisible(true);
        DefaultColor = new Color(255,255,255);
        ClickedColor = new Color(71,134,246);
        
        dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dashboard_gt = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        bien_gt = new javax.swing.JLabel();
        contact_gt = new javax.swing.JLabel();
        contrat_gt = new javax.swing.JLabel();
        maintenance_gt = new javax.swing.JLabel();
        finance_gt = new javax.swing.JLabel();
        message_gt = new javax.swing.JLabel();
        gestionnaire = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 235, 240));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(253, 700));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home1.png"))); // NOI18N
        jLabel1.setText("GESTION-IMMO");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        dashboard_gt.setBackground(new java.awt.Color(255, 255, 255));
        dashboard_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        dashboard_gt.setForeground(new java.awt.Color(51, 51, 51));
        dashboard_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N
        dashboard_gt.setText("Tableau de board");
        dashboard_gt.setOpaque(true);
        dashboard_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboard_gtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dashboard_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(dashboard_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        bien_gt.setBackground(new java.awt.Color(255, 255, 255));
        bien_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        bien_gt.setForeground(new java.awt.Color(51, 51, 51));
        bien_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bien.png"))); // NOI18N
        bien_gt.setText("Biens Immobiliers");
        bien_gt.setOpaque(true);
        bien_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bien_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bien_gtMousePressed(evt);
            }
        });

        contact_gt.setBackground(new java.awt.Color(255, 255, 255));
        contact_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        contact_gt.setForeground(new java.awt.Color(51, 51, 51));
        contact_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Contact.png"))); // NOI18N
        contact_gt.setText("Contacts");
        contact_gt.setOpaque(true);
        contact_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contact_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contact_gtMousePressed(evt);
            }
        });

        contrat_gt.setBackground(new java.awt.Color(255, 255, 255));
        contrat_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        contrat_gt.setForeground(new java.awt.Color(51, 51, 51));
        contrat_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/contrat.png"))); // NOI18N
        contrat_gt.setText("contrats");
        contrat_gt.setOpaque(true);
        contrat_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contrat_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrat_gtMousePressed(evt);
            }
        });

        maintenance_gt.setBackground(new java.awt.Color(255, 255, 255));
        maintenance_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        maintenance_gt.setForeground(new java.awt.Color(51, 51, 51));
        maintenance_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maintenance.png"))); // NOI18N
        maintenance_gt.setText("Maintenance");
        maintenance_gt.setOpaque(true);
        maintenance_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintenance_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maintenance_gtMousePressed(evt);
            }
        });

        finance_gt.setBackground(new java.awt.Color(255, 255, 255));
        finance_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        finance_gt.setForeground(new java.awt.Color(51, 51, 51));
        finance_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance.png"))); // NOI18N
        finance_gt.setText("Finance");
        finance_gt.setOpaque(true);
        finance_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finance_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                finance_gtMousePressed(evt);
            }
        });

        message_gt.setBackground(new java.awt.Color(255, 255, 255));
        message_gt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        message_gt.setForeground(new java.awt.Color(51, 51, 51));
        message_gt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/message.png"))); // NOI18N
        message_gt.setText("visite");
        message_gt.setOpaque(true);
        message_gt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                message_gtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                message_gtMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(contact_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maintenance_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finance_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(contrat_gt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(bien_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(message_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bien_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contact_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contrat_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maintenance_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(finance_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(message_gt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        gestionnaire.setPreferredSize(new java.awt.Dimension(1000, 400));

        javax.swing.GroupLayout gestionnaireLayout = new javax.swing.GroupLayout(gestionnaire);
        gestionnaire.setLayout(gestionnaireLayout);
        gestionnaireLayout.setHorizontalGroup(
            gestionnaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        gestionnaireLayout.setVerticalGroup(
            gestionnaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionnaire, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(gestionnaire, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(ClickedColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(DefaultColor);
    }//GEN-LAST:event_dashboard_gtMousePressed

    private void bien_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bien_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(ClickedColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(DefaultColor);
    }//GEN-LAST:event_bien_gtMousePressed

    private void contact_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(ClickedColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(DefaultColor);
    }//GEN-LAST:event_contact_gtMousePressed

    private void contrat_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrat_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(ClickedColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(DefaultColor);
    }//GEN-LAST:event_contrat_gtMousePressed

    private void maintenance_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenance_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(ClickedColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(DefaultColor);
    }//GEN-LAST:event_maintenance_gtMousePressed

    private void finance_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finance_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(ClickedColor);
        message_gt.setBackground(DefaultColor);
    }//GEN-LAST:event_finance_gtMousePressed

    private void message_gtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_message_gtMousePressed
        // TODO add your handling code here:
         dashboard_gt.setBackground(DefaultColor);
        bien_gt.setBackground(DefaultColor);
        contact_gt.setBackground(DefaultColor);
        contrat_gt.setBackground(DefaultColor);
        maintenance_gt.setBackground(DefaultColor);
        finance_gt.setBackground(DefaultColor);
        message_gt.setBackground(ClickedColor);
    }//GEN-LAST:event_message_gtMousePressed

    private void dashboard_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_gtMouseClicked
        // TODO add your handling code here:
        DashboardGestionnaire dashboardGestionnaire = new DashboardGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(dashboardGestionnaire).setVisible(true);
    }//GEN-LAST:event_dashboard_gtMouseClicked

    private void bien_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bien_gtMouseClicked
        // TODO add your handling code here:
        Bien Bien = new Bien();
        gestionnaire.removeAll();
        gestionnaire.add(Bien).setVisible(true);
    }//GEN-LAST:event_bien_gtMouseClicked

    private void contact_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contact_gtMouseClicked
        // TODO add your handling code here:
        ContactGestionnaire ContactGestionnaire = new ContactGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(ContactGestionnaire).setVisible(true);
    }//GEN-LAST:event_contact_gtMouseClicked

    private void contrat_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrat_gtMouseClicked
        // TODO add your handling code here:
        ContratGestionnaire ContratGestionnaire = new ContratGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(ContratGestionnaire).setVisible(true);
    }//GEN-LAST:event_contrat_gtMouseClicked

    private void maintenance_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenance_gtMouseClicked
        // TODO add your handling code here:
        MaintenanceGestionnaire MaintenanceGestionnaire = new MaintenanceGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(MaintenanceGestionnaire).setVisible(true);
    }//GEN-LAST:event_maintenance_gtMouseClicked

    private void finance_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finance_gtMouseClicked
        // TODO add your handling code here:
        FinanceGestionnaire FinanceGestionnaire = new FinanceGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(FinanceGestionnaire).setVisible(true);
    }//GEN-LAST:event_finance_gtMouseClicked

    private void message_gtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_message_gtMouseClicked
        // TODO add your handling code here:
        visiteGestionnaire MessageGestionnaire = new visiteGestionnaire();
        gestionnaire.removeAll();
        gestionnaire.add(MessageGestionnaire).setVisible(true);
    }//GEN-LAST:event_message_gtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionnaireForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionnaireForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bien_gt;
    private javax.swing.JLabel contact_gt;
    private javax.swing.JLabel contrat_gt;
    private javax.swing.JLabel dashboard_gt;
    private javax.swing.JLabel finance_gt;
    private javax.swing.JDesktopPane gestionnaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel maintenance_gt;
    private javax.swing.JLabel message_gt;
    // End of variables declaration//GEN-END:variables
}
